spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/gestion_plantillas
    username: admin_rh
    password: password_rh
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true