spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/gestion_plantillas
    username: admin_rh
    password: password_rh
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  # CREDENCIALES DE ACTUATOR
  security:
    user:
      name: ${ACTUATOR_USER:actuator_dev}
      password: ${ACTUATOR_PASSWORD:actuator_dev}

  boot:
    admin:
      client:
        url: http://localhost:9090/admin
        username: admin_dev
        password: admin_dev
        instance:
          name: GestorRH-API
          management-base-url: http://localhost:8080
          metadata:
            management.username: ${ACTUATOR_USER:actuator_dev}
            management.password: ${ACTUATOR_PASSWORD:actuator_dev}

logging:
  level:
    root: WARN
    com.gestorrh.api: INFO

# CONFIGURACIÓN DE SEGURIDAD (JWT).
jwt:
  secret: ${JWT_SECRET:zXo9cM8yK2qR6aT7vN1bW5eH3gJ6fL0uP0sD8aA2kV4=}
  expiration: 86400000