server {
    listen 80;
    server_name gestorrh.ddns.net;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name gestorrh.ddns.net;

    ssl_certificate     /etc/letsencrypt/live/gestorrh.ddns.net/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/gestorrh.ddns.net/privkey.pem;

    client_max_body_size 10M;

    location /admin {
        proxy_pass         http://127.0.0.1:9090;
        proxy_set_header   Host $host;
        proxy_set_header   X-Real-IP $remote_addr;
        proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto $scheme;
        proxy_set_header   X-Forwarded-Host $host;
        proxy_set_header   X-Forwarded-Prefix /admin;
        proxy_connect_timeout 60s;
        proxy_read_timeout 60s;
    }

    location /actuator/health {
        proxy_pass         http://127.0.0.1:8080;
        proxy_set_header   Host $host;
        proxy_set_header   X-Real-IP $remote_addr;
        proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto $scheme;
        proxy_set_header   X-Forwarded-Host $host;
        proxy_connect_timeout 60s;
        proxy_read_timeout 60s;
    }

    location /actuator/ {
        deny all;
        return 403;
    }

    location / {
        proxy_pass         http://127.0.0.1:8080;
        proxy_set_header   Host $host;
        proxy_set_header   X-Real-IP $remote_addr;
        proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto $scheme;
        proxy_set_header   X-Forwarded-Host $host;
        proxy_set_header   X-Forwarded-Prefix "";
        proxy_connect_timeout 60s;
        proxy_read_timeout 60s;
    }
}