-- ============================================================
-- V1__esquema_inicial.sql
-- Esquema inicial de GestorRH generado desde la base de datos
-- real en estado v1.4.1
-- ============================================================

CREATE TABLE empresa (
                         id_empresa  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         direccion   CHARACTER VARYING(255) NOT NULL,
                         email       CHARACTER VARYING(100) NOT NULL,
                         latitud_sede  DOUBLE PRECISION,
                         longitud_sede DOUBLE PRECISION,
                         nombre      CHARACTER VARYING(100) NOT NULL,
                         password    CHARACTER VARYING(255) NOT NULL,
                         radio_validez INTEGER,
                         telefono    CHARACTER VARYING(20) NOT NULL,
                         CONSTRAINT uk2fqlxbcs4h827hio1qam0dhd3 UNIQUE (nombre),
                         CONSTRAINT uka485s5bp9jdf8sbt8fhgunr1i UNIQUE (telefono),
                         CONSTRAINT uknfu2qgep9eyw4f7jpxoxix8ci UNIQUE (email)
);

CREATE TABLE empleado (
                          id_empleado         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          activo              BOOLEAN NOT NULL,
                          apellidos           CHARACTER VARYING(150) NOT NULL,
                          departamento        CHARACTER VARYING(100),
                          email               CHARACTER VARYING(100) NOT NULL,
                          fecha_baja_contrato DATE,
                          nombre              CHARACTER VARYING(100) NOT NULL,
                          password            CHARACTER VARYING(255) NOT NULL,
                          puesto              CHARACTER VARYING(100),
                          rol                 CHARACTER VARYING(255) NOT NULL,
                          telefono            CHARACTER VARYING(20),
                          empresa_id          BIGINT NOT NULL,
                          CONSTRAINT empleado_rol_check CHECK (rol IN ('EMPLEADO', 'SUPERVISOR')),
                          CONSTRAINT uknihg474u49g6e8aolp4lwrj6e UNIQUE (email),
                          CONSTRAINT fkhw0kus5ohyrrpf1xo13fjpuik FOREIGN KEY (empresa_id) REFERENCES empresa (id_empresa)
);

CREATE TABLE turno (
                       id_turno    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       descripcion CHARACTER VARYING(100) NOT NULL,
                       hora_fin    TIME(0) WITHOUT TIME ZONE NOT NULL,
                       hora_inicio TIME(0) WITHOUT TIME ZONE NOT NULL,
                       empresa_id  BIGINT NOT NULL,
                       CONSTRAINT fkn24shni2ulr21juf84f8h3yt4 FOREIGN KEY (empresa_id) REFERENCES empresa (id_empresa)
);

CREATE TABLE asignacion_turno (
                                  id_asignacion      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                  fecha              DATE NOT NULL,
                                  fecha_cambio       TIMESTAMP(6) WITH TIME ZONE,
                                  modalidad          CHARACTER VARYING(255) NOT NULL,
                                  motivo_cambio      CHARACTER VARYING(255),
                                  responsable_cambio CHARACTER VARYING(100),
                                  version            BIGINT,
                                  empleado_id        BIGINT NOT NULL,
                                  turno_id           BIGINT NOT NULL,
                                  CONSTRAINT asignacion_turno_modalidad_check CHECK (modalidad IN ('PRESENCIAL', 'TELETRABAJO')),
                                  CONSTRAINT fkkek9cyd9rd4594nb9wv1mt186 FOREIGN KEY (empleado_id) REFERENCES empleado (id_empleado),
                                  CONSTRAINT fkkrpejm7nrr4oy9h1lhiy404f6 FOREIGN KEY (turno_id)    REFERENCES turno (id_turno)
);

CREATE TABLE ausencia (
                          id_ausencia            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          descripcion            CHARACTER VARYING(255),
                          estado                 CHARACTER VARYING(255) NOT NULL,
                          fecha_fin              DATE NOT NULL,
                          fecha_inicio           DATE NOT NULL,
                          justificante           CHARACTER VARYING(500),
                          observaciones_revision CHARACTER VARYING(255),
                          responsable_revision   CHARACTER VARYING(100),
                          tipo                   CHARACTER VARYING(255) NOT NULL,
                          version                BIGINT,
                          empleado_id            BIGINT NOT NULL,
                          CONSTRAINT ausencia_estado_check CHECK (estado IN ('SOLICITADA', 'APROBADA', 'RECHAZADA')),
                          CONSTRAINT ausencia_tipo_check   CHECK (tipo   IN ('MEDICA', 'VACACIONES', 'MOTIVO_PERSONAL', 'OTROS')),
                          CONSTRAINT fkihhs4n9dwdvh4uft7immvbtgs FOREIGN KEY (empleado_id) REFERENCES empleado (id_empleado)
);

CREATE TABLE fichaje (
                         id_fichaje       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         fecha            DATE NOT NULL,
                         hora_entrada     TIMESTAMP(6) WITH TIME ZONE NOT NULL,
                         hora_salida      TIMESTAMP(6) WITH TIME ZONE,
                         incidencias      CHARACTER VARYING(500),
                         latitud_entrada  DOUBLE PRECISION,
                         latitud_salida   DOUBLE PRECISION,
                         longitud_entrada DOUBLE PRECISION,
                         longitud_salida  DOUBLE PRECISION,
                         asignacion_id    BIGINT,
                         empleado_id      BIGINT NOT NULL,
                         CONSTRAINT fkbyj7vu36pye83q1d9yo3dmhbq FOREIGN KEY (empleado_id)  REFERENCES empleado (id_empleado),
                         CONSTRAINT fkrihhh9qbl626ccx5sm7mnkh78 FOREIGN KEY (asignacion_id) REFERENCES asignacion_turno (id_asignacion)
);